### ISSUE TITLE
Handling multiple external authentication providers

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#103]
Right now user is able to log in with Google and then add other external accounts, e.g. Microsoft. But he/she also has the right to remove the Google account afterwards. 
![image](https://user-images.githubusercontent.com/42002784/45304578-f2c4ef00-b54a-11e8-9da1-abad17493124.png)

I think we need to add some constraint here. Otherwise user would end up like this,
![image](https://user-images.githubusercontent.com/42002784/45304692-3586c700-b54b-11e8-8287-58ab3041e0db.png)

**Comment by d33pspace** [comment]
@elainetao829 Thanks for noticing this. I think this made sense under our previous model where the user was able to enter an email of their choice upon logging in through a 3rd party provider. Now there is no choice given at least for Gmail and Microsoft, so you're right. This would not make sense. If a user signed in with both Gmail and Microsoft they would have two different accounts.

**Comment by elainetao829** [comment]
1. It's still possible to add a microsoft account when logged in with goggle already.
2. Facebook also provides a email. But if user logged in with Google or Microsoft, and tries to add a Facebook, the system would return an error. Also if user logged in with a Facebook account, no microsoft nor Google account can be added.
![image](https://user-images.githubusercontent.com/42002784/45558522-b5c26a80-b872-11e8-95d8-ae245d4eb7fa.png)

3. I think we should change the whole manage external account workflow. User logs in with one external account should not be able to add another. This does not make any sense and I doubt if anyone would do that in the real life.

**Comment by d33pspace** [comment]
@elainetao829 Thank you. I agree and I'll discuss this with Girish.

**Comment by elainetao829** [comment]
Hi @d33pspace,
I would need to take some time to see if I can register a Facebook account with my google account since I've already got a Facebook account.

The following scenario has been test which is similar here,
I registered in Renewal with my 163 mailbox. I also have a Microsoft account register with 163 account. So when I tried to log in with Microsoft account, the system 
a. told me that this account has been registered.
b. disabled the email field and did not allow me to change the mailbox (this is correct I know).
c. provide a log in button so I can go to the log in page again.

I think your scenario would lead to the same result. 

By the way, in the past I registered with my Facebook account, and the system allowed me to enter a name/mailbox. So I entered something randomly.  This function has been changed now, but the old data has not been taken care of (at least in staging). I'm not sure if you want to take care of this, or in order to let customer use the website smoothly, we can keep the old data as it was.

**Comment by d33pspace** [comment]
@elainetao829 Aha. Ok. This make sense. Thank you. But now I'm inclined to leave the Manage External Accounts feature intact because I think what you just tried is a reasonable scenario. (Establishing a local account normally with a password, and then deciding later to use an external provider to sign in. The only way to accomplish this is from the Manage External Accounts panel.) 

So please continue testing external provider authentication and let's discuss any errors or oddities you run into. By the way, the original issue you opened this ticket was adding Google, then Microsoft, then removing Google. While I agree this would be strange and unlikely, as long as no error occurs and the user can continue to sign in with Microsoft I think it should be fine.

And by the way, I don't feel like we need to push the testing on external authentication to the limits right now. Just try a few things you think would be typical use cases. We might push the testing further here once we add WeChat authentication.

**Comment by elainetao829** [comment]
Hi @d33pspace, I tested this functionality for a while and there is no new finding. I would close this for now and if anything found I will open a new one.
