### ISSUE TITLE
Managment external account page is not translated into Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#41]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/44408895-e07f1300-a593-11e8-8137-3eccedd8b8e5.png)

Expected Result:
Manage your external logins.
管理您的第三方登录账户

Registered Logins
已注册账户

Add another service to log in.
新增一个第三方登录账户

**Comment by d33pspace** [comment]
Please check. I implemented the translation but wasn't able to check it myself because I don't have external login set up. 

Also, do you think we should translate Google and Microsoft? Or perhaps have both the English and Chinese (e.g. "Microsoft 微软") for Chinese language selection? I imagine it's not necessary for Google but perhaps would be useful for Microsoft?

**Comment by elainetao829** [comment]
@d33pspace I would say we don't need to translate that. I think if a Chinese holds a Microsoft account, he/she would definitely know it's 微软。I haven't found any examples though.

And if we want to translate that, I would suggest we translate all of them. It would be weird to have 1 Chinese and 2 English buttons together. For Facebook, it's 脸书, for Google, it's 谷歌。

**Comment by d33pspace** [comment]
@kolte Please implement translation for
Microsoft 微软
Google 谷歌
Facebook 脸书

**Comment by d33pspace** [comment]
Also here please :)

![inkedscreenshot 175 _li](https://user-images.githubusercontent.com/13606352/44616624-b6746c00-a885-11e8-8bbe-8599d5805623.jpg)

**Comment by elainetao829** [comment]
Verified and confirm fixed.
