### ISSUE TITLE
The error message on the details page is not translated correctly.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#44]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/44443916-caf9ff80-a60c-11e8-91fc-1a1545603e4f.png)
The 全名 field is required. 

Expected Result:
请输入您的全名。

**Comment by d33pspace** [comment]
@elainetao829 This error message format may apply to any field and the translation needs to be in a similar format if possible, "The ______ filed is required." So would "请输入您的_____" also work for any other field, such as "请输入您的州/省“? It sounds okay to me but just wanted you to consider from this angle. Also, let's use just 省 instead of 州/省 for Chinese pages. Do you think so?

**Comment by elainetao829** [comment]
let's use just 省 instead of 州/省  -- agree.

 "The ______ filed is required." So would "请输入您的_____" also work for any other field,   -- agree

But on this page, there is no other mandatory field. Do you want to change some of them to be mandatory as well?

**Comment by elainetao829** [comment]
Hi @kolte,
I noticed you have changed  全名 into 姓名 because of another ticket. That's great. Then please also update the message here from,
请输入您的全名。 --> 请输入您的姓名。
![image](https://user-images.githubusercontent.com/42002784/44786717-92879200-abc7-11e8-905b-e3d88e790856.png)

**Comment by d33pspace** [comment]
I've searched for all occurrences of 全名 and replaced with 姓名 so I believe I got this.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
